# Generated by Django 5.2.3 on 2025-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
