# Generated by Django 5.2.3 on 2025-08-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
