# Generated by Django 5.2.3 on 2025-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
